name: ShelfSpeak
main: pyromanic.ShelfSpeak.ShelfSpeak
version: 0.7
commands:
     shelf:
          description:
          usage: 
     shelfcolors:
          description:
          usage:
     shelfwrite:
          description:
          usage:
     shelflock:
          description:
          usage:
     shelfline:
          description:
          usage:
     shelfclear:
          description:
          usage:
     shelfremove:
          description:
          usage:
     shelfcancel:
          description:
          usage:
     shelfimport:
          description:
          usage:
     shelfsave:
          description:
          usage: